cmd /c certutil -addstore -f "Root" C:\vagrant\resources\addtrust_external_ca.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\baltimore_ca.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\digicert.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\equifax.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\globalsign.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\gte_cybertrust.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\microsoft_root_2011.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\thawte_primary_root.cer
cmd /c certutil -addstore -f "Root" C:\vagrant\resources\utn-userfirst.cer